Fix ECR login and add install-awscli script

diff --git a/scripts/ecr-public-login b/scripts/ecr-public-login
--- a/scripts/ecr-public-login
+++ b/scripts/ecr-public-login
@@ -1,9 +1,21 @@
 #!/bin/bash
 set -euo pipefail
 
+SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
+BUILD_DIR=$SCRIPTPATH/../build/
+export PATH="${BUILD_DIR}:${PATH}"
+
 if [[ -z "${ECR_REGISTRY}" ]]; then
     echo "The env var ECR_REGISTRY must be set"
     exit 1
 fi
 
-docker login --username AWS -p="$(docker run --rm --env-file <(env | grep AWS) -i amazon/aws-cli ecr-public get-login-password --region us-east-1)" ${ECR_REGISTRY}
+function exit_and_fail() {
+    echo "❌ Failed to login to ECR Public Repo!"
+}
+
+trap exit_and_fail INT TERM ERR
+
+"${SCRIPTPATH}/install-awscli"
+
+docker login --username AWS --password="$(aws ecr-public get-login-password --region us-east-1)" "${ECR_REGISTRY}"
