Refactors for log and error handling for eventhandlers. Refacors for ASG launch lifecycle bash script
Refactored interruption event handling into a seperate package with distinct handlers for different interruption event Kinds. Updated ASG launch lifecycle hook acceptance test and eks-cluster run-test

diff --git a/test/e2e/asg-launch-lifecycle-sqs-test b/test/e2e/asg-launch-lifecycle-sqs-test
--- a/test/e2e/asg-launch-lifecycle-sqs-test
+++ b/test/e2e/asg-launch-lifecycle-sqs-test
@@ -1,10 +1,7 @@
 #!/bin/bash
 set -euo pipefail
 
-REGION="us-west-2"
-CLUSTER_NAME="nth-eks-cluster-test"
-
-node_group_name="nth-eks-cluster-test-spot-ng"
+node_group_name="spot-ng"
 sqs_queue_name="nth-sqs-test"
 sns_topic_name="nth-sns-test"
 node_policy_name="nth-test-node-policy"
@@ -47,9 +44,9 @@ EOF
 
 cat << EOF > /tmp/queue-attributes.json
 {
-"MessageRetentionPeriod": "300",
-"Policy": "$(echo $sqs_queue_policy | sed 's/\"/\\"/g' | tr -d -s '\n' " ")",
-"SqsManagedSseEnabled": "true"
+    "MessageRetentionPeriod": "300",
+    "Policy": "$(echo $sqs_queue_policy | sed 's/\"/\\"/g' | tr -d -s '\n' " ")",
+    "SqsManagedSseEnabled": "true"
 }
 EOF
 
@@ -140,6 +137,15 @@ EOF
 
 ##### SETUP #####
 
+function validate_aws_account {
+    if [[ -n "$account_id" ]]; then
+        echo "🥑 AWS Account ID: $account_id"
+    else
+        echo "❌ Failed to retrieve AWS Account ID ❌"
+        exit 1
+    fi
+}
+
 ### SQS ###
 function provision_sqs_queue {
     queue_exists=$(aws sqs list-queues --queue-name-prefix $sqs_queue_name)
@@ -178,27 +184,8 @@ function subscribe_sqs_to_sns {
 }
 
 ### NODEGROUP ###
-function provision_node_group {
+function update_node_group {
     create_node_policy
-    node_group_exists=$(eksctl get nodegroup --cluster=$CLUSTER_NAME --name $node_group_name || :)
-    if [[ -n $node_group_exists ]]; then
-        get_node_role_name
-        delete_node_group
-        echo ""
-
-        node_group_exists=$(eksctl get nodegroup --cluster=$CLUSTER_NAME --name $node_group_name || :)
-        echo -n "Node group Deleting."
-        while [[ -n $node_group_exists ]]; do
-            echo -n "."
-            node_group_exists=$(eksctl get nodegroup --cluster=$CLUSTER_NAME --name $node_group_name || :)
-            sleep 10
-        done
-        echo ""
-        sleep 20
-    fi
-
-    echo "🥑 Provisioning Spot Node Group"
-    eksctl create nodegroup --config-file=$NODE_GROUP_CONFIG_FILE
 
     echo "🥑 Attaching Node policy to Node role"
     get_node_role_name
@@ -332,7 +319,8 @@ function start_FIS_experiment {
     create_FIS_role
     create_experiment_template
     echo "🥑 Starting Experiment"
-    experiment_start_time=$(aws fis start-experiment --experiment-template-id $template_id | jq -r '.experiment.startTime')
+    experiment_start_time=$(date +%s)
+    experiment=$(aws fis start-experiment --experiment-template-id $template_id)
 }
 
 
@@ -344,20 +332,51 @@ function is_new_instance {
     fi
 }
 
+function convert_date_to_epoch_seconds {
+    IFS='T' read -r date_part time_part <<< "$1"
+    IFS='-' read -r year month day <<< "$date_part"
+    IFS=':' read -r hour minute second_fractional <<< "$time_part"
+    IFS='.' read -r second fraction <<< "$second_fractional"
+    IFS=':' read -r offset_hours offset_minutes <<< "${time_part:16:5}"
+
+    if [[ $time_part =~ .*"-".* ]]; then
+        offset_hours=$((offset_hours * -1))
+        offset_minutes=$((offset_minutes * -1))
+    fi
+
+    total_days=$(((year - 1970) * 365 + (year - 1970)/4))
+    for ((i = 1; i < month; i++)); do
+        total_days=$((total_days + $(cal $i $year | awk 'NF {DAYS = $NF} END {print DAYS}')))
+    done
+    total_days=$((total_days + day - 1))
+    total_seconds=$((total_days * 86400 + (hour + offset_hours) * 3600 + (minute + offset_minutes) * 60 + second))
+}
+
 function get_launch_activity {
+    max_duration=$((5 * 60))
+    start_time=$(date +%s)
+
     launch_activity=""
-    while [[ -z $launch_activity  ]]; do
+    while [[ -z $launch_activity ]]; do
+        current_time=$(date +%s)
+        elapsed_time=$((current_time - start_time))
+        if [[ $elapsed_time -ge $max_duration ]]; then 
+            echo "❌ Failed to find a new launched instance. Timeout Reached ❌"
+            exit 1
+        fi
+
         sleep 5
         activities=$(aws autoscaling describe-scaling-activities --auto-scaling-group-name $asg_name)
-        activities_details=$(jq -r '[.Activities | .[] | .ActivityId, .Description, .StatusCode]' <<< $activities)
+        activities_details=$(jq -r '[.Activities | .[] | .ActivityId, .Description, .StatusCode, .StartTime]' <<< $activities)
         num_activities=$(jq -r 'length' <<< $activities_details)
-        for i in $(seq 0 3 $((--num_activities))); do
+        for i in $(seq 0 4 $((--num_activities))); do
             id=$(jq -r .[$i] <<< $activities_details)
             description=$(jq -r .[$((++i))] <<< $activities_details)
             status=$(jq -r .[$((i+=2))] <<< $activities_details)
+            start=$(jq -r .[$((i+=3))] <<< $activities_details)
             activity_instance=${description##*:}
-            is_new_instance $activity_instance
-            if [[ $description =~ .*"Launching".* && $is_new == "true" ]]; then
+            convert_date_to_epoch_seconds $start
+            if [[ $description =~ .*"Launching".* && $total_seconds -gt $experiment_start_time ]]; then
                 launch_activity=$id
                 echo "🥑 Launch Activity found for instance $activity_instance"
                 break
@@ -369,20 +388,35 @@ function get_launch_activity {
 function test_launch_lifecycle {
     aws sqs receive-message --queue-url $queue_url
     echo -n "🥑 Waiting for launch hook completion."
+
+    max_duration=$((4 * 60))
+    start_time=$(date +%s)
     while [[ true ]]; do
+        current_time=$(date +%s)
+        elapsed_time=$((current_time - start_time))
+        if [[ $elapsed_time -ge $max_duration ]]; then 
+            echo ""
+            echo "❌ Launch Lifecycle not Completed. Timeout Reached ❌"
+            exit 1
+        fi
+
         activity_status=$(aws autoscaling describe-scaling-activities --auto-scaling-group-name $asg_name --activity-ids $launch_activity | jq -r '.Activities | .[].StatusCode')
         if [[ $activity_status == "Successful" ]]; then
             echo ""
             echo "✅ Launch Lifecycle Successfully Completed ✅"
-            exit_policy="exit 0"
-            break
+            exit 0
         fi
 
         if [[ $activity_status == "Cancelled" ]]; then
             echo ""
+            echo "❌ Launch Lifecycle Cancelled ❌"
+            exit 1
+        fi
+
+        if [[ $activity_status == "Failed" ]]; then
+            echo ""
             echo "❌ Launch Lifecycle Failed ❌"
-            exit_policy="exit 1"
-            break
+            exit 1
         fi
         echo -n "."
         sleep 10
@@ -395,27 +429,43 @@ function clean_up {
     echo "====================================================================================================="
     echo "🧹  Cleaning up SQS, SNS, NodeGroup, IAM, FIS  🧹"
     echo "====================================================================================================="
-    pod_id=$(get_nth_worker_pod || :)
-    kubectl logs $pod_id --namespace kube-system || :
+    print_logs
     echo "🥑 Uninstalling NTH helm chart"
     helm uninstall "$CLUSTER_NAME-acth" -n kube-system
     delete_node_group
-    echo "🥑 Unsubscribing SNS from SQS"
-    aws sns unsubscribe --subscription-arn $subscription_arn
-    echo "🥑 Deleting SQS queue"
-    aws sqs delete-queue --queue-url $queue_url
-    echo "🥑 Deleting SNS topic"
-    aws sns delete-topic --topic-arn $sns_arn
-    echo "🥑 Deleting FIS experiment template"
-    deletedTemplate=$(aws fis delete-experiment-template --id $template_id --no-paginate)
+    if [[ -n $subscription_arn ]]; then 
+        echo "🥑 Unsubscribing SNS from SQS"
+        aws sns unsubscribe --subscription-arn $subscription_arn
+    fi 
+    if [[ -n $queue_url ]]; then 
+        echo "🥑 Deleting SQS queue"
+        aws sqs delete-queue --queue-url $queue_url
+    fi
+    if [[ -n $sns_arn ]]; then 
+        echo "🥑 Deleting SNS topic"
+        aws sns delete-topic --topic-arn $sns_arn
+    fi
+    if [[ -n $template_id ]]; then 
+        echo "🥑 Deleting FIS experiment template"
+        deletedTemplate=$(aws fis delete-experiment-template --id $template_id --no-paginate)
+    fi
     echo "🥑 Detaching FIS role policy"
     aws iam detach-role-policy --role-name $fis_role_name --policy-arn $fis_policy_arn
     echo "🥑 Deleting FIS role"
     aws iam delete-role --role-name $fis_role_name
     echo "🥑 Deleting autoscaling role"
     aws iam delete-service-linked-role --role-name $auto_scaling_role_name
-    echo "🥑 Deleting Node role policy"
-    aws iam delete-policy --policy-arn $node_policy_arn
+    if [[ -n $node_policy_arn ]]; then
+        echo "🥑 Deleting Node role policy"
+        aws iam delete-policy --policy-arn $node_policy_arn
+    fi
+}
+
+function print_logs {
+    pod_id=$(get_nth_worker_pod || :)
+    if [[ -n $pod_id ]]; then
+        kubectl logs $pod_id --namespace kube-system || :
+    fi
 }
 
 function delete_node_group {
@@ -426,21 +476,15 @@ function delete_node_group {
         echo "🥑 Detaching NTH Node Group policy"
         aws iam detach-role-policy --role-name $node_role_name --policy-arn $node_policy_arn
     fi
-    echo "🥑 Deleting NTH Node Group"
-    eksctl delete nodegroup -f $NODE_GROUP_CONFIG_FILE --approve
 }
 
-function main {
-    provision_sqs_queue
-    provision_sns_topic    
-    subscribe_sqs_to_sns
-    provision_node_group
-    install_helm
-    start_FIS_experiment
-    get_launch_activity
-    test_launch_lifecycle
-    trap "clean_up" EXIT
-    eval $exit_policy
-}
-
-main
+trap "clean_up" EXIT
+validate_aws_account
+provision_sqs_queue
+provision_sns_topic    
+subscribe_sqs_to_sns
+update_node_group
+install_helm
+start_FIS_experiment
+get_launch_activity
+test_launch_lifecycle
