Update ec2-metadata-test-proxy to support tolerations
For scheduled event cancellation test, add tolerations to
the proxy to allow it to schedule to emit the cancellation event.

diff --git a/test/e2e/maintenance-event-cancellation-test b/test/e2e/maintenance-event-cancellation-test
--- a/test/e2e/maintenance-event-cancellation-test
+++ b/test/e2e/maintenance-event-cancellation-test
@@ -32,13 +32,16 @@ helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-meta
   --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG" \
   --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true" \
   --set ec2MetadataTestProxy.enableSpotITN="false" \
-  --set ec2MetadataTestProxy.port="$IMDS_PORT"
+  --set ec2MetadataTestProxy.port="$IMDS_PORT" \
+  --set 'ec2MetadataTestProxy.tolerations[0].effect=NoSchedule' \
+  --set 'ec2MetadataTestProxy.tolerations[0].operator=Exists'
 
 TAINT_CHECK_CYCLES=15
 TAINT_CHECK_SLEEP=15
 
 DEPLOYED=0
 CORDONED=0
+TAINTED=0
 
 for i in `seq 1 10`; do
     if [[ $(kubectl get deployments regular-pod-test -o jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
@@ -57,6 +60,12 @@ fi
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
     if kubectl get nodes $CLUSTER_NAME-worker --no-headers | grep SchedulingDisabled; then
         echo "✅ Verified the worker node was cordoned!"
+
+        if kubectl get nodes $CLUSTER_NAME-worker -o json | grep "aws-node-termination-handler/scheduled-maintenance"; then
+          echo "✅ Verified the worked node was tainted!"
+          TAINTED=1
+        fi
+
         if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
             echo "✅ Verified the regular-pod-test pod was evicted!"
             CORDONED=1
@@ -71,6 +80,11 @@ if [[ $CORDONED -eq 0 ]]; then
     exit 3
 fi
 
+if [[ $TAINTED -eq 0 ]]; then
+    echo "❌ Failed tainting node for scheduled maintenance event"
+    exit 3
+fi
+
 helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/ \
   --wait \
   --force \
@@ -80,7 +94,9 @@ helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-meta
   --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true" \
   --set ec2MetadataTestProxy.enableSpotITN="false" \
   --set ec2MetadataTestProxy.scheduledEventStatus="canceled" \
-  --set ec2MetadataTestProxy.port="$IMDS_PORT"    
+  --set ec2MetadataTestProxy.port="$IMDS_PORT" \
+  --set 'ec2MetadataTestProxy.tolerations[0].effect=NoSchedule' \
+  --set 'ec2MetadataTestProxy.tolerations[0].operator=Exists'
 
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
     if kubectl get nodes $CLUSTER_NAME-worker --no-headers | grep -v SchedulingDisabled; then
diff --git a/test/e2e/maintenance-event-reboot-test b/test/e2e/maintenance-event-reboot-test
--- a/test/e2e/maintenance-event-reboot-test
+++ b/test/e2e/maintenance-event-reboot-test
@@ -35,6 +35,7 @@ TAINT_CHECK_SLEEP=15
 
 DEPLOYED=0
 CORDONED=0
+TAINTED=0
 
 for i in `seq 1 10`; do
     if [[ $(kubectl get deployments regular-pod-test -o jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
@@ -52,7 +53,13 @@ fi
 
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
     if kubectl get nodes $CLUSTER_NAME-worker | grep SchedulingDisabled; then
-        echo "✅ Verified the worker node was cordoned!"
+        echo "✅ Verified the worker node was cordoned for maintenance event reboot!"
+
+        if kubectl get nodes $CLUSTER_NAME-worker -o json | grep "aws-node-termination-handler/scheduled-maintenance"; then
+          echo "✅ Verified the worked node was tainted!"
+          TAINTED=1
+        fi
+
         if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
             echo "✅ Verified the regular-pod-test pod was evicted!"
             CORDONED=1
@@ -64,6 +71,11 @@ done
 
 if [[ $CORDONED -eq 0 ]]; then
     echo "❌ Failed cordoning node for scheduled maintenance event"
+    exit 3
+fi
+
+if [[ $TAINTED -eq 0 ]]; then
+    echo "❌ Failed tainting node for scheduled maintenance event"
     exit 3
 fi
 
@@ -94,6 +106,15 @@ for i in `seq 1 $TAINT_CHECK_CYCLES`; do
     NODE_LINE=$(kubectl get nodes $CLUSTER_NAME-worker | grep -v 'STATUS')
     if [[ -z $(echo $NODE_LINE | grep SchedulingDisabled) ]] && [[ ! -z $(echo $NODE_LINE | grep Ready) ]]; then
         echo "✅ Verified the worker node was uncordoned!"
+
+        if ! kubectl get nodes $CLUSTER_NAME-worker -o json | grep "aws-node-termination-handler/scheduled-maintenance"; then
+          echo "✅ Verified the worked node was untainted!"
+          TAINTED=0
+        else
+          echo "❌ Failed clearing the worked node taint after a reboot!"
+          exit 3
+        fi
+
         if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
             echo "✅ Verified the regular-pod-test pod was rescheduled"
             echo "✅ Scheduled Maintenance Event System Reboot Test Passed $CLUSTER_NAME! ✅"
diff --git a/test/e2e/maintenance-event-test b/test/e2e/maintenance-event-test
--- a/test/e2e/maintenance-event-test
+++ b/test/e2e/maintenance-event-test
@@ -53,9 +53,19 @@ if [[ $DEPLOYED -eq 0 ]]; then
     exit 2
 fi
 
+TAINTED=0
+
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
     if kubectl get nodes $CLUSTER_NAME-worker | grep SchedulingDisabled; then
         echo "✅ Verified the worker node was cordoned!"
+
+        if kubectl get nodes $CLUSTER_NAME-worker -o json | grep "aws-node-termination-handler/scheduled-maintenance"; then
+          echo "✅ Verified the worked node was tainted!"
+        else
+          echo "❌ Failed tainting node for maintenance event"
+          exit 3
+        fi
+
         if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
             echo "✅ Verified the regular-pod-test pod was evicted!"
             echo "✅ Scheduled Maintenance Event Handling Test Passed $CLUSTER_NAME! ✅"
diff --git a/test/e2e/spot-interruption-test b/test/e2e/spot-interruption-test
--- a/test/e2e/spot-interruption-test
+++ b/test/e2e/spot-interruption-test
@@ -55,6 +55,14 @@ fi
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
       if kubectl get nodes $CLUSTER_NAME-worker | grep SchedulingDisabled; then
           echo "✅ Verified the worker node was cordoned!"
+
+          if kubectl get nodes $CLUSTER_NAME-worker -o json | grep "aws-node-termination-handler/spot-itn"; then
+            echo "✅ Verified the worked node was tainted!"
+          else
+            echo "❌ Failed tainting node for spot termination event"
+            exit 3
+          fi
+
           if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
               echo "✅ Verified the regular-pod-test pod was evicted!"
               echo "✅ Spot Interruption Test Passed $CLUSTER_NAME! ✅"
