add Windows node support (#185)
* add Windows node support

* fix system test mock for k8s <1.14

* fix syntax error

* fix unit tests

* fix gofmt issues

* increase test coverage

* add make target to run unit tests in linux container

* add uptime stub for darwin

diff --git a/test/e2e/maintenance-event-cancellation-test b/test/e2e/maintenance-event-cancellation-test
--- a/test/e2e/maintenance-event-cancellation-test
+++ b/test/e2e/maintenance-event-cancellation-test
@@ -10,37 +10,69 @@ set -euo pipefail
 #   $EC2_METADATA_DOCKER_REPO
 #   $EC2_METADATA_DOCKER_TAG
 
+function fail_and_exit {
+    echo "❌ Test Maintenance Event Cancellation failed $CLUSTER_NAME ❌"
+    exit ${1:-1}
+}
+
 echo "Starting Maintenance Event Cancellation Test for Node Termination Handler"
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 
-helm upgrade --install $CLUSTER_NAME-anth $SCRIPTPATH/../../config/helm/aws-node-termination-handler/ \
-  --wait \
-  --namespace kube-system \
-  --set instanceMetadataURL="http://localhost:$IMDS_PORT" \
-  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO" \
-  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG" \
-  --set enableSpotInterruptionDraining="true" \
-  --set enableScheduledEventDraining="true" \
-  --set taintNode="true"
+common_helm_args=()
+[[ "${TEST_WINDOWS-}" == "true" ]] && common_helm_args+=(--set targetNodeOs="windows")
 
-helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/ \
-  --wait \
-  --namespace default \
-  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO" \
-  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG" \
-  --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true" \
-  --set ec2MetadataTestProxy.enableSpotITN="false" \
-  --set ec2MetadataTestProxy.port="$IMDS_PORT" \
-  --set 'ec2MetadataTestProxy.tolerations[0].effect=NoSchedule' \
+anth_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-anth
+  $SCRIPTPATH/../../config/helm/aws-node-termination-handler/
+  --wait
+  --namespace kube-system
+  --set instanceMetadataURL=${INSTANCE_METADATA_URL:-"http://localhost:$IMDS_PORT"}
+  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO"
+  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG"
+  --set enableSpotInterruptionDraining="true"
+  --set enableScheduledEventDraining="true"
+  --set taintNode="true"
+)
+[[ -n "${NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY-}" ]] &&
+    anth_helm_args+=(--set image.pullPolicy="$NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    anth_helm_args+=("${common_helm_args[@]}")
+
+set -x
+helm "${anth_helm_args[@]}"
+set +x
+
+emtp_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-emtp
+  $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/
+  --wait
+  --namespace default
+  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO"
+  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG"
+  --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true"
+  --set ec2MetadataTestProxy.enableSpotITN="false"
+  --set ec2MetadataTestProxy.port="$IMDS_PORT"
+  --set 'ec2MetadataTestProxy.tolerations[0].effect=NoSchedule'
   --set 'ec2MetadataTestProxy.tolerations[0].operator=Exists'
+)
+[[ -n "${EC2_METADATA_DOCKER_PULL_POLICY-}" ]] &&
+    emtp_helm_args+=(--set ec2MetadataTestProxy.image.pullPolicy="$EC2_METADATA_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    emtp_helm_args+=("${common_helm_args[@]}")
+
+set -x
+helm "${emtp_helm_args[@]}"
+set +x
 
 TAINT_CHECK_CYCLES=15
 TAINT_CHECK_SLEEP=15
 
 DEPLOYED=0
-CORDONED=0
-TAINTED=0
 
 for i in `seq 1 10`; do
     if [[ $(kubectl get deployments regular-pod-test -o jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
@@ -52,60 +84,85 @@ for i in `seq 1 10`; do
 done
 
 if [[ $DEPLOYED -eq 0 ]]; then
-    echo "❌ Failed test setup for regular-pod"
-    exit 2
+    echo "❌ regular-pod-test pod deployment failed"
+    fail_and_exit 2
 fi
 
+cordoned=0
+tainted=0
+evicted=0
+test_node=${TEST_NODE:-$CLUSTER_NAME-worker}
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
-    if kubectl get nodes $CLUSTER_NAME-worker --no-headers | grep SchedulingDisabled; then
+    if [[ $cordoned -eq 0 ]] && kubectl get nodes $test_node --no-headers | grep SchedulingDisabled >/dev/null; then
         echo "✅ Verified the worker node was cordoned!"
+        cordoned=1
+    fi
 
-        if kubectl get nodes $CLUSTER_NAME-worker -o json | grep -q "aws-node-termination-handler/scheduled-maintenance"; then
-          echo "✅ Verified the worked node was tainted!"
-          TAINTED=1
-        fi
+    if [[ $cordoned -eq 1 && $tainted -eq 0 ]] && kubectl get nodes $test_node -o json | grep -q "aws-node-termination-handler/scheduled-maintenance" >/dev/null; then
+      echo "✅ Verified the worked node was tainted!"
+      tainted=1
+    fi
 
-        if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
-            echo "✅ Verified the regular-pod-test pod was evicted!"
-            CORDONED=1
-            break
-        fi
+    if [[ $tainted -eq 1 && $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
+        echo "✅ Verified the regular-pod-test pod was evicted!"
+        evicted=1
+        break
     fi
     sleep $TAINT_CHECK_SLEEP
 done
 
-if [[ $CORDONED -eq 0 ]]; then
-    echo "❌ Failed cordoning node for scheduled maintenance event"
-    exit 3
+if [[ $cordoned -eq 0 ]]; then
+    echo "❌ Worker node was not cordoned"
+    fail_and_exit 1
+elif [[ $tainted -eq 0 ]]; then
+    echo "❌ Worker node was not tainted"
+    fail_and_exit 1
+elif [[ $evicted -eq 0 ]]; then
+    echo "❌ regular-pod-test pod was not evicted"
+    fail_and_exit 1
 fi
 
-if [[ $TAINTED -eq 0 ]]; then
-    echo "❌ Failed tainting node for scheduled maintenance event"
-    exit 3
-fi
-
-helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/ \
-  --wait \
-  --namespace default \
-  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO" \
-  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG" \
-  --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true" \
-  --set ec2MetadataTestProxy.enableSpotITN="false" \
-  --set ec2MetadataTestProxy.scheduledEventStatus="canceled" \
-  --set ec2MetadataTestProxy.port="$IMDS_PORT" \
-  --set 'ec2MetadataTestProxy.tolerations[0].effect=NoSchedule' \
+emtp_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-emtp
+  $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/
+  --wait
+  --namespace default
+  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO"
+  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG"
+  --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true"
+  --set ec2MetadataTestProxy.enableSpotITN="false"
+  --set ec2MetadataTestProxy.scheduledEventStatus="canceled"
+  --set ec2MetadataTestProxy.port="$IMDS_PORT"
+  --set 'ec2MetadataTestProxy.tolerations[0].effect=NoSchedule'
   --set 'ec2MetadataTestProxy.tolerations[0].operator=Exists'
+)
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    emtp_helm_args+=("${common_helm_args[@]}")
 
+set -x
+helm "${emtp_helm_args[@]}"
+set +x
+
+uncordoned=0
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
-    if kubectl get nodes $CLUSTER_NAME-worker --no-headers | grep -v SchedulingDisabled; then
+    if [[ $uncordoned -eq 0 ]] && kubectl get nodes $test_node --no-headers | grep -v SchedulingDisabled >/dev/null; then
         echo "✅ Verified the worker node was uncordoned!"
-        if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
-            echo "✅ Verified the regular-pod-test pod was rescheduled"
-            echo "✅ Scheduled Maintenance Event Cancellation Test Passed $CLUSTER_NAME! ✅"
-            exit 0
-        fi
+        uncordoned=1
+    fi
+
+    if [[ $uncordoned -eq 1 && $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
+        echo "✅ Verified the regular-pod-test pod was rescheduled"
+        echo "✅ Test Maintenance Event Cancellation passed! $CLUSTER_NAME ✅"
+        exit 0
     fi
     sleep $TAINT_CHECK_SLEEP
 done
 
-exit 1
+if [[ $uncordoned -eq 0 ]]; then
+    echo "❌ Worker node was not UNcordoned"
+else
+    echo "❌ regular-pod-test pod was not rescheduled"
+fi
+fail_and_exit 1
diff --git a/test/e2e/maintenance-event-reboot-test b/test/e2e/maintenance-event-reboot-test
--- a/test/e2e/maintenance-event-reboot-test
+++ b/test/e2e/maintenance-event-reboot-test
@@ -6,124 +6,184 @@ set -euo pipefail
 #   $CLUSTER_NAME
 #   $KUBECONFIG
 
+function fail_and_exit {
+    echo "❌ Scheduled Maintenance Event System Reboot Test failed $CLUSTER_NAME ❌"
+    exit ${1:-1}
+}
+
 echo "Starting Maintenance Event Cancellation Test for Node Termination Handler"
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 
-helm upgrade --install $CLUSTER_NAME-anth $SCRIPTPATH/../../config/helm/aws-node-termination-handler/ \
-  --wait \
-  --force \
-  --namespace kube-system \
-  --set instanceMetadataURL="http://localhost:$IMDS_PORT" \
-  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO" \
-  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG" \
-  --set enableSpotInterruptionDraining="true" \
-  --set enableScheduledEventDraining="true" \
-  --set taintNode="true"
+common_helm_args=()
+[[ "${TEST_WINDOWS-}" == "true" ]] && common_helm_args+=(--set targetNodeOs="windows")
 
-helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/ \
-  --wait \
-  --force \
-  --namespace default \
-  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO" \
-  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG" \
-  --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true" \
-  --set ec2MetadataTestProxy.enableSpotITN="false" \
+anth_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-anth
+  $SCRIPTPATH/../../config/helm/aws-node-termination-handler/
+  --wait
+  --force
+  --namespace kube-system
+  --set instanceMetadataURL=${INSTANCE_METADATA_URL:-"http://localhost:$IMDS_PORT"}
+  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO"
+  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG"
+  --set enableSpotInterruptionDraining="true"
+  --set enableScheduledEventDraining="true"
+  --set taintNode="true"
+)
+[[ -n "${NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY-}" ]] &&
+    anth_helm_args+=(--set image.pullPolicy="$NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    anth_helm_args+=("${common_helm_args[@]}")
+
+set -x
+helm "${anth_helm_args[@]}"
+set +x
+
+emtp_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-emtp
+  $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/
+  --wait
+  --force
+  --namespace default
+  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO"
+  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG"
+  --set ec2MetadataTestProxy.enableScheduledMaintenanceEvents="true"
+  --set ec2MetadataTestProxy.enableSpotITN="false"
   --set ec2MetadataTestProxy.port="$IMDS_PORT"
+)
+[[ -n "${EC2_METADATA_DOCKER_PULL_POLICY-}" ]] &&
+    emtp_helm_args+=(--set ec2MetadataTestProxy.image.pullPolicy="$EC2_METADATA_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    emtp_helm_args+=("${common_helm_args[@]}")
+
+set -x
+helm "${emtp_helm_args[@]}"
+set +x
 
 TAINT_CHECK_CYCLES=15
 TAINT_CHECK_SLEEP=15
 
-DEPLOYED=0
-CORDONED=0
-TAINTED=0
-
+deployed=0
 for i in `seq 1 10`; do
     if [[ $(kubectl get deployments regular-pod-test -o jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
         echo "✅ Verified regular-pod-test pod was scheduled and started!"
-        DEPLOYED=1
+        deployed=1
         break
     fi
     sleep 5
 done
 
-if [[ $DEPLOYED -eq 0 ]]; then
+if [[ $deployed -eq 0 ]]; then
     echo "❌ Failed test setup for regular-pod"
-    exit 2
+    fail_and_exit 2
 fi
 
+cordoned=0
+tainted=0
+evicted=0
+test_node=${TEST_NODE:-$CLUSTER_NAME-worker}
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
-    if kubectl get nodes $CLUSTER_NAME-worker | grep SchedulingDisabled; then
+    if [[ $cordoned -eq 0 ]] && kubectl get nodes $test_node | grep SchedulingDisabled >/dev/null; then
         echo "✅ Verified the worker node was cordoned for maintenance event reboot!"
+        cordoned=1
+    fi
 
-        if kubectl get nodes $CLUSTER_NAME-worker -o json | grep "aws-node-termination-handler/scheduled-maintenance"; then
-          echo "✅ Verified the worked node was tainted!"
-          TAINTED=1
-        fi
+    if [[ $cordoned -eq 1 ]] && kubectl get nodes $test_node -o json | grep "aws-node-termination-handler/scheduled-maintenance" >/dev/null; then
+      echo "✅ Verified the worker node was tainted!"
+      tainted=1
+    fi
 
-        if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
-            echo "✅ Verified the regular-pod-test pod was evicted!"
-            CORDONED=1
-            break
-        fi
+    if [[ $tainted -eq 1 && $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
+        echo "✅ Verified the regular-pod-test pod was evicted!"
+        evicted=1
+        break
     fi
     sleep $TAINT_CHECK_SLEEP
 done
 
-if [[ $CORDONED -eq 0 ]]; then
+if [[ $cordoned -eq 0 ]]; then
     echo "❌ Failed cordoning node for scheduled maintenance event"
-    exit 3
+    fail_and_exit 3
 fi
 
-if [[ $TAINTED -eq 0 ]]; then
+if [[ $tainted -eq 0 ]]; then
     echo "❌ Failed tainting node for scheduled maintenance event"
-    exit 3
+    fail_and_exit 3
 fi
 
-## Copy uptime file to Kind k8s nodes
-for node in $(kubectl get nodes -o json | jq -r '.items[].metadata.name'); do
-    docker exec $node sh -c "rm -rf /uptime"
-    docker cp $SCRIPTPATH/../assets/uptime-reboot $node:/uptime
-    docker exec $node sh -c "chmod 0444 /uptime && chown root /uptime && chgrp root /uptime"
-done
+mock_uptime_filepath="/uptime"
+if [[ "${TEST_WINDOWS:-"false"}" != "true" ]]; then
+    echo "Copy uptime file to Kind k8s nodes"
+    for node in $(kubectl get nodes -o json | jq -r '.items[].metadata.name'); do
+        docker exec $node sh -c "rm -rf $mock_uptime_filepath"
+        docker cp $SCRIPTPATH/../assets/uptime-reboot $node:$mock_uptime_filepath
+        docker exec $node sh -c "chmod 0444 $mock_uptime_filepath && chown root $mock_uptime_filepath && chgrp root $mock_uptime_filepath"
+    done
+else
+    echo "Copy uptime file to $TEST_NODE"
+    kubectl cp $SCRIPTPATH/../assets/uptime-root kube-system/$(get_nth_worker_pod):$mock_uptime_filepath
+fi
 
-## Remove ec2-metadata-test-proxy to prevent another drain event but keep regular-test-pod
+echo "Remove ec2-metadata-test-proxy to prevent another drain event but keep regular-test-pod"
 daemonset=$(kubectl get daemonsets | grep 'ec2-metadata-test-proxy' | cut -d' ' -f1)
 kubectl delete daemonsets $daemonset
 
 ## Restart NTH which will simulate a system reboot by mounting a new uptime file
-helm upgrade --install $CLUSTER_NAME-anth $SCRIPTPATH/../../config/helm/aws-node-termination-handler/ \
-  --wait \
-  --force \
-  --namespace kube-system \
-  --set instanceMetadataURL="http://localhost:$IMDS_PORT" \
-  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO" \
-  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG" \
-  --set procUptimeFile="/uptime" \
-  --set enableSpotInterruptionDraining="true" \
-  --set enableScheduledEventDraining="true" \
+anth_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-anth
+  $SCRIPTPATH/../../config/helm/aws-node-termination-handler/
+  --wait
+  --force
+  --namespace kube-system
+  --set instanceMetadataURL=${INSTANCE_METADATA_URL:-"http://localhost:$IMDS_PORT"}
+  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO"
+  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG"
+  --set procUptimeFile=$mock_uptime_filepath
+  --set enableSpotInterruptionDraining="true"
+  --set enableScheduledEventDraining="true"
   --set taintNode="true"
+)
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    anth_helm_args+=("${common_helm_args[@]}")
 
+set -x
+helm "${anth_helm_args[@]}"
+set +x
+
+uncordoned=0
+untainted=0
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
-    NODE_LINE=$(kubectl get nodes $CLUSTER_NAME-worker | grep -v 'STATUS')
-    if [[ -z $(echo $NODE_LINE | grep SchedulingDisabled) ]] && [[ ! -z $(echo $NODE_LINE | grep Ready) ]]; then
+    NODE_LINE=$(kubectl get nodes $test_node | grep -v 'STATUS')
+    if [[ $uncordoned -eq 0 && -z $(echo $NODE_LINE | grep SchedulingDisabled) ]] && [[ ! -z $(echo $NODE_LINE | grep Ready) ]]; then
         echo "✅ Verified the worker node was uncordoned!"
+        uncordoned=1
+    fi
 
-        if ! kubectl get nodes $CLUSTER_NAME-worker -o json | grep -q "aws-node-termination-handler/scheduled-maintenance"; then
-          echo "✅ Verified the worked node was untainted!"
-          TAINTED=0
-        else
-          echo "❌ Failed clearing the worked node taint after a reboot!"
-          exit 3
-        fi
+    if [[ $uncordoned -eq 1 && $untainted -eq 0 ]] && ! kubectl get nodes $test_node -o json | grep -q "aws-node-termination-handler/scheduled-maintenance" >/dev/null; then
+      echo "✅ Verified the worked node was untainted!"
+      untainted=1
+    fi
 
-        if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
-            echo "✅ Verified the regular-pod-test pod was rescheduled"
-            echo "✅ Scheduled Maintenance Event System Reboot Test Passed $CLUSTER_NAME! ✅"
-            exit 0
-        fi
+    if [[ $untainted -eq 1 && $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
+        echo "✅ Verified the regular-pod-test pod was rescheduled"
+        echo "✅ Scheduled Maintenance Event System Reboot Test Passed $CLUSTER_NAME! ✅"
+        exit 0
     fi
     sleep $TAINT_CHECK_SLEEP
 done
 
-exit 1
+if [[ $uncordoned -eq 0 ]]; then
+    echo "❌ Worker node was not UNcordoned"
+elif [[ $untainted -eq 0 ]]; then
+    echo "❌ Worked node was not UNtainted"
+else
+    echo "❌ regular-pod-test pod was not rescheduled"
+fi
+fail_and_exit 1
diff --git a/test/e2e/spot-interruption-dry-run-test b/test/e2e/spot-interruption-dry-run-test
--- a/test/e2e/spot-interruption-dry-run-test
+++ b/test/e2e/spot-interruption-dry-run-test
@@ -10,41 +10,83 @@ set -euo pipefail
 #   $EC2_METADATA_DOCKER_REPO
 #   $EC2_METADATA_DOCKER_TAG
 
+function fail_and_exit {
+    echo "❌ Spot Interruption Dry Run test failed $CLUSTER_NAME ❌"
+    exit ${1:-1}
+}
+
 echo "Starting Maintenance Events Dry-Run Test for Node Termination Handler"
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 
-helm upgrade --install $CLUSTER_NAME-anth $SCRIPTPATH/../../config/helm/aws-node-termination-handler/ \
-  --wait \
-  --force \
-  --namespace kube-system \
-  --set instanceMetadataURL="http://localhost:$IMDS_PORT" \
-  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO" \
-  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG" \
-  --set dryRun="true" \
-  --set enableSpotInterruptionDraining="true" \
+common_helm_args=()
+[[ "${TEST_WINDOWS-}" == "true" ]] && common_helm_args+=(--set targetNodeOs="windows")
+
+anth_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-anth
+  $SCRIPTPATH/../../config/helm/aws-node-termination-handler/
+  --wait
+  --force
+  --namespace kube-system
+  --set instanceMetadataURL=${INSTANCE_METADATA_URL:-"http://localhost:$IMDS_PORT"}
+  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO"
+  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG"
+  --set dryRun="true"
+  --set enableSpotInterruptionDraining="true"
   --set enableScheduledEventDraining="true"
+)
+[[ -n "${NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY-}" ]] &&
+    anth_helm_args+=(--set image.pullPolicy="$NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    anth_helm_args+=("${common_helm_args[@]}")
 
-helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/ \
-  --wait \
-  --force \
-  --namespace default \
-  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO" \
-  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG" \
+set -x
+helm "${anth_helm_args[@]}"
+set +x
+
+emtp_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-emtp
+  $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/
+  --wait
+  --force
+  --namespace default
+  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO"
+  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG"
   --set ec2MetadataTestProxy.port="$IMDS_PORT"
+)
+[[ -n "${EC2_METADATA_DOCKER_PULL_POLICY-}" ]] &&
+    emtp_helm_args+=(--set ec2MetadataTestProxy.image.pullPolicy="$EC2_METADATA_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    emtp_helm_args+=("${common_helm_args[@]}")
 
+set -x
+helm "${emtp_helm_args[@]}"
+set +x
 
+logs=0
+pod_id=$(get_nth_worker_pod)
+test_node=${TEST_NODE:-$CLUSTER_NAME-worker}
 for i in $(seq 0 10); do
-  POD_ID=$(get_nth_worker_pod)
-  if [[ ! -z $(kubectl logs $POD_ID -n kube-system | grep -i -e 'would have been cordoned and drained') ]]; then
+  if [[ $logs -eq 0 && ! -z $(kubectl logs $pod_id -n kube-system | grep -i -e 'would have been cordoned and drained') ]]; then
       echo "✅ Verified the dryrun logs were executed"
-      if kubectl get nodes $CLUSTER_NAME-worker --no-headers | grep -v SchedulingDisabled; then
-          echo "✅ Verified the worker node was not cordoned!"
-          echo "✅ Spot Interruption Dry Run Test Passed $CLUSTER_NAME! ✅"
-          exit 0
-      fi
+      logs=1
+  fi
+
+  if [[ $logs -eq 1 ]] && kubectl get nodes $test_node --no-headers | grep -v SchedulingDisabled >/dev/null; then
+      echo "✅ Verified the worker node was not cordoned!"
+      echo "✅ Spot Interruption Dry Run Test Passed $CLUSTER_NAME! ✅"
+      exit 0
   fi
   sleep 10
 done
 
-exit 1
+if [[ $logs -eq 0 ]]; then
+    echo "❌ dryrun logs were not executed"
+else
+    echo "❌ Worker node was cordoned"
+fi
+fail_and_exit 1
diff --git a/test/e2e/webhook-http-proxy-test b/test/e2e/webhook-http-proxy-test
--- a/test/e2e/webhook-http-proxy-test
+++ b/test/e2e/webhook-http-proxy-test
@@ -10,6 +10,11 @@ set -euo pipefail
 #   $EC2_METADATA_DOCKER_REPO
 #   $EC2_METADATA_DOCKER_TAG
 
+function fail_and_exit {
+    echo "❌ Webhook HTTP Proxy Test failed $CLUSTER_NAME ❌"
+    exit ${1:-1}
+}
+
 echo "Starting Webhook HTTP Proxy Test for Node Termination Handler"
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
@@ -17,10 +22,9 @@ SQUID_DOCKERHUB_IMG="sameersbn/squid:3.5.27-2@sha256:e98299069f0c6e3d9b918890351
 SQUID_DOCKER_IMG="squid:customtest"
 
 ### LOCAL ONLY TESTS FOR 200 RESPONSE FROM LOCAL CLUSTER, MASTER WILL TEST WITH TRAVIS SECRET URL
-if [[ -z $(env | grep "WEBHOOK_URL=") ]]; then
+if [[ -z "${WEBHOOK_URL-}" ]]; then
   WEBHOOK_URL="http://127.0.0.1:$IMDS_PORT"
 fi
-
 
 docker pull $SQUID_DOCKERHUB_IMG
 docker tag $SQUID_DOCKERHUB_IMG $SQUID_DOCKER_IMG
@@ -39,65 +43,108 @@ helm upgrade --install $CLUSTER_NAME-squid $SCRIPTPATH/../../config/helm/squid/ 
 
 sleep 20
 
-helm upgrade --install $CLUSTER_NAME-anth $SCRIPTPATH/../../config/helm/aws-node-termination-handler/ \
-  --force \
-  --namespace kube-system \
-  --set instanceMetadataURL="http://localhost:$IMDS_PORT" \
-  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO" \
-  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG" \
-  --set enableSpotInterruptionDraining="true" \
-  --set enableScheduledEventDraining="true" \
-  --set webhookURL="$WEBHOOK_URL" \
-  --set webhookTemplate="\{\"Content\":\"[NTH][Instance Interruption] InstanceId: \{\{ \.InstanceID \}\} - InstanceType: \{\{ \.InstanceType \}\} - Kind: \{\{ \.Kind \}\} - Start Time: \{\{ \.StartTime \}\}\"\}" \
-  --set webhookProxy="tcp://localhost:3128"
+common_helm_args=()
+[[ "${TEST_WINDOWS-}" == "true" ]] && common_helm_args+=(--set targetNodeOs="windows")
 
-helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/ \
-  --force \
-  --namespace default \
-  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO" \
-  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG" \
-  --set ec2MetadataTestProxy.enableSpotITN="true" \
+anth_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-anth
+  $SCRIPTPATH/../../config/helm/aws-node-termination-handler/
+  --force
+  --namespace kube-system
+  --set instanceMetadataURL="http://localhost:$IMDS_PORT"
+  --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO"
+  --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG"
+  --set enableSpotInterruptionDraining="true"
+  --set enableScheduledEventDraining="true"
+  --set webhookURL="$WEBHOOK_URL"
+  --set webhookTemplate="\{\"Content\":\"[NTH][Instance Interruption] InstanceId: \{\{ \.InstanceID \}\} - InstanceType: \{\{ \.InstanceType \}\} - Kind: \{\{ \.Kind \}\} - Start Time: \{\{ \.StartTime \}\}\"\}"
+  --set webhookProxy="tcp://localhost:3128"
+)
+[[ -n "${NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY-}" ]] &&
+    anth_helm_args+=(--set image.pullPolicy="$NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    anth_helm_args+=("${common_helm_args[@]}")
+
+set -x
+helm "${anth_helm_args[@]}"
+set +x
+
+emtp_helm_args=(
+  upgrade
+  --install
+  $CLUSTER_NAME-emtp
+  $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/
+  --force
+  --namespace default
+  --set ec2MetadataTestProxy.image.repository="$EC2_METADATA_DOCKER_REPO"
+  --set ec2MetadataTestProxy.image.tag="$EC2_METADATA_DOCKER_TAG"
+  --set ec2MetadataTestProxy.enableSpotITN="true"
   --set ec2MetadataTestProxy.port="$IMDS_PORT"
+)
+[[ -n "${EC2_METADATA_DOCKER_PULL_POLICY-}" ]] &&
+    emtp_helm_args+=(--set ec2MetadataTestProxy.image.pullPolicy="$EC2_METADATA_DOCKER_PULL_POLICY")
+[[ ${#common_helm_args[@]} -gt 0 ]] &&
+    emtp_helm_args+=("${common_helm_args[@]}")
+
+set -x
+helm "${emtp_helm_args[@]}"
+set +x
 
 TAINT_CHECK_CYCLES=15
 TAINT_CHECK_SLEEP=15
 
-DEPLOYED=0
-
+deployed=0
 for i in `seq 1 10`; do 
     if [[ $(kubectl get deployments regular-pod-test -o jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
         echo "✅ Verified regular-pod-test pod was scheduled and started!"
-        DEPLOYED=1
+        deployed=1
         break
     fi
     sleep 5
 done 
 
-if [[ $DEPLOYED -eq 0 ]]; then
-    exit 2
+if [[ $deployed -eq 0 ]]; then
+    echo "❌ regular-pod-test pod deployment failed"
+    fail_end_exit 2
 fi
 
+cordoned=0
+evicted=0
+sent=0
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
-      if kubectl get nodes $CLUSTER_NAME-worker | grep SchedulingDisabled; then
-          echo "✅ Verified the worker node was cordoned!"
-          if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
-              echo "✅ Verified the regular-pod-test pod was evicted!"
-              NTH_POD_NAME=$(get_nth_worker_pod)
-              if kubectl logs $NTH_POD_NAME -n kube-system | grep 'Webhook Success'; then
-                echo "✅ Webhook Successfully Sent $CLUSTER_NAME! ✅"
-                pods=$(kubectl get pods -o json)
-                ## queries for the squid pod on the worker node
-                squid_worker_pods=$(echo $pods | jq '.items[] | select( .metadata.name | contains("squid") ) | .metadata.name as $name | select( .spec.nodeName | contains("worker") ) | .spec.nodeName as $nodename | $name' -r)
-                ## return only 1 pod
-                if kubectl exec -it $(echo $squid_worker_pods | cut -d' ' -f1) -- cat /var/log/squid/access.log | grep -e 'TCP_MISS/200' -e 'TCP_TUNNEL/200' -e 'TCP_MISS_ABORTED/200'; then
-                    echo "✅ Verified the webhook POST used the http proxy"
-                    exit 0
-                fi
-              fi
-          fi
+  if [[ $cordoned -eq 0 ]] && kubectl get nodes $CLUSTER_NAME-worker | grep SchedulingDisabled; then
+      echo "✅ Verified the worker node was cordoned!"
+      cordoned=1
+  fi
 
-      fi
-    sleep $TAINT_CHECK_SLEEP
+  if [[ $cordoned -eq 1 && $evicted -eq 0 && $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
+      echo "✅ Verified the regular-pod-test pod was evicted!"
+      evicted=1
+      pod_id=$(get_nth_worker_pod)
+  fi
+
+  if [[ $evicted -eq 1 && $sent -eq 0 ]] && kubectl logs $pod_id -n kube-system | grep 'Webhook Success' >/dev/null; then
+    echo "✅ Verified that webhook successfully sent"
+    sent=1
+    squid_worker_pods=$(kubectl get pods -o json | jq '.items[] | select( .metadata.name | contains("squid") ) | .metadata.name as $name | select( .spec.nodeName | contains("worker") ) | .spec.nodeName as $nodename | $name' -r)
+  fi
+
+  if [[ $sent -eq 1 ]] && kubectl exec -it $(echo $squid_worker_pods | cut -d' ' -f1) -- cat /var/log/squid/access.log | grep -e 'TCP_MISS/200' -e 'TCP_TUNNEL/200' -e 'TCP_MISS_ABORTED/200' >/dev/null; then
+     echo "✅ Verified the webhook POST used the http proxy"
+        exit 0
+  fi
+  sleep $TAINT_CHECK_SLEEP
 done
 
-exit 1
+if [[ $cordoned -eq 0 ]]; then
+    echo "❌ Worker node was not cordoned"
+elif [[ $evicted -eq 0 ]]; then
+    echo "❌ regular-pod-test pod was not evicted"
+elif [[ $sent -eq 0 ]]; then
+    echo "❌ Webhook not sent"
+else
+    echo "❌ Webhook POST did not use http proxy"
+fi
+fail_and_exit 1
