Taint nodes on spot and scheduled events (#162)
* Taint nodes on spot and scheduled events

Fixes #160.

Signed-off-by: Ilya Shaisultanov <ilya.shaisultanov@gmail.com>

diff --git a/test/e2e/spot-interruption-test b/test/e2e/spot-interruption-test
--- a/test/e2e/spot-interruption-test
+++ b/test/e2e/spot-interruption-test
@@ -22,7 +22,8 @@ helm upgrade --install $CLUSTER_NAME-anth $SCRIPTPATH/../../config/helm/aws-node
   --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO" \
   --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG" \
   --set enableScheduledEventDraining="false" \
-  --set enableSpotInterruptionDraining="true" 
+  --set enableSpotInterruptionDraining="true" \
+  --set taintNode="true"
 
 helm upgrade --install $CLUSTER_NAME-emtp $SCRIPTPATH/../../config/helm/ec2-metadata-test-proxy/ \
   --wait \
@@ -55,6 +56,14 @@ fi
 for i in `seq 1 $TAINT_CHECK_CYCLES`; do
       if kubectl get nodes $CLUSTER_NAME-worker | grep SchedulingDisabled; then
           echo "✅ Verified the worker node was cordoned!"
+
+          if kubectl get nodes $CLUSTER_NAME-worker -o json | grep -q "aws-node-termination-handler/spot-itn"; then
+            echo "✅ Verified the worked node was tainted!"
+          else
+            echo "❌ Failed tainting node for spot termination event"
+            exit 3
+          fi
+
           if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
               echo "✅ Verified the regular-pod-test pod was evicted!"
               echo "✅ Spot Interruption Test Passed $CLUSTER_NAME! ✅"
