feat: ability to emit Kubernetes events (#411)

diff --git a/test/e2e/spot-interruption-test-events-on b/test/e2e/spot-interruption-test-events-on
--- a/test/e2e/spot-interruption-test-events-on
+++ b/test/e2e/spot-interruption-test-events-on
@@ -13,11 +13,11 @@ set -euo pipefail
 #   $AEMM_VERSION
 
 function fail_and_exit {
-    echo "❌ Rebalance Recommendation Drain test failed $CLUSTER_NAME ❌"
-    exit "${1:-1}"
+    echo "❌ Spot Interruption With Events test failed $CLUSTER_NAME ❌"
+    exit ${1:-1}
 }
 
-echo "Starting Rebalance Recommendation Drain Test for Node Termination Handler"
+echo "Starting Spot Interruption With Events Test for Node Termination Handler"
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 
@@ -37,10 +37,11 @@ anth_helm_args=(
   --set image.repository="$NODE_TERMINATION_HANDLER_DOCKER_REPO"
   --set image.tag="$NODE_TERMINATION_HANDLER_DOCKER_TAG"
   --set enableScheduledEventDraining="false"
-  --set enableSpotInterruptionDraining="false"
-  --set enableRebalanceDraining="true"
+  --set enableSpotInterruptionDraining="true"
   --set taintNode="true"
   --set tolerations=""
+  --set emitKubernetesEvents="true"
+  --set kubernetesEventsExtraAnnotations="spot.itn.events/test=extra-annotation"
 )
 [[ -n "${NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY-}" ]] &&
     anth_helm_args+=(--set image.pullPolicy="$NODE_TERMINATION_HANDLER_DOCKER_PULL_POLICY")
@@ -79,12 +80,10 @@ aemm_helm_args=(
   --wait
   --namespace default
   --set servicePort="$IMDS_PORT"
-  --set aemm.mockDelaySec=60
   --set 'tolerations[0].effect=NoSchedule'
   --set 'tolerations[0].operator=Exists'
   --set arguments='{spot}'
 )
-
 [[ ${#common_helm_args[@]} -gt 0 ]] &&
     aemm_helm_args+=("${common_helm_args[@]}")
 
@@ -96,7 +95,7 @@ TAINT_CHECK_CYCLES=15
 TAINT_CHECK_SLEEP=15
 
 deployed=0
-for i in $(seq 1 $TAINT_CHECK_CYCLES); do
+for i in `seq 1 $TAINT_CHECK_CYCLES`; do
     if [[ $(kubectl get deployments regular-pod-test -o jsonpath='{.status.unavailableReplicas}') -eq 0 ]]; then
         echo "✅ Verified regular-pod-test pod was scheduled and started!"
         deployed=1
@@ -114,19 +113,19 @@ fi
 cordoned=0
 tainted=0
 evicted=0
-test_node="${TEST_NODE:-$CLUSTER_NAME-worker}"
-for i in $(seq 1 $TAINT_CHECK_CYCLES); do
-    if [[ $cordoned -eq 0 ]] && kubectl get nodes "${test_node}" | grep SchedulingDisabled > /dev/null; then
+test_node=${TEST_NODE:-$CLUSTER_NAME-worker}
+for i in `seq 1 $TAINT_CHECK_CYCLES`; do
+    if [[ $cordoned -eq 0 ]] && kubectl get nodes $test_node | grep SchedulingDisabled >/dev/null; then
         echo "✅ Verified the worker node was cordoned!"
         cordoned=1
     fi
 
-    if [[ $cordoned -eq 1 ]] && kubectl get nodes "${test_node}" -o json | grep "aws-node-termination-handler/rebalance-recommendation" >/dev/null; then
-        echo "✅ Verified the worker node was tainted!"
+    if [[ $cordoned -eq 1 && $tainted -eq 0 ]] && kubectl get nodes $test_node -o json | grep -q "aws-node-termination-handler/spot-itn" >/dev/null; then
+        echo "✅ Verified the worked node was tainted!"
         tainted=1
     fi
 
-    if [[ $cordoned -eq 1 && $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
+    if [[ $tainted -eq 1 && $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
         echo "✅ Verified the regular-pod-test pod was evicted!"
         evicted=1
         break
@@ -136,27 +135,55 @@ for i in $(seq 1 $TAINT_CHECK_CYCLES); do
 done
 
 if [[ $cordoned -eq 0 ]]; then
-  echo "❌ Worker node was not cordoned"
-  fail_and_exit 3
+    echo "❌ Worker node was not cordoned"
+    fail_and_exit 3
 elif [[ $tainted -eq 0 ]]; then
-  echo "❌ Worker node was not tainted"
-  fail_and_exit 3
+    echo "❌ Worker node was not tainted"
+    fail_and_exit 3
 elif [[ $evicted -eq 0 ]]; then
-  echo "❌ regular-pod-test not was evicted"
-  fail_and_exit 3
+    echo "❌ regular-pod-test pod was not evicted"
+    fail_and_exit 3
 fi
 
-echo "🥑 Waiting for Rebalance Recommendation..."
-# Rebalance Recommendation will eventually become available since aemm.MockDelaySec will not exceed TAINT_CHECK_CYCLES x TAINT_CHECK_SLEEP
-for i in $(seq 1 $TAINT_CHECK_CYCLES); do
-    if [[ $(kubectl get deployments regular-pod-test -o=jsonpath='{.status.unavailableReplicas}') -eq 1 ]]; then
-        echo "✅ Verified the regular-pod-test pod was evicted!"
-        echo "✅ Rebalance Recommendation Drain Test Passed $CLUSTER_NAME! ✅"
+echo "🥑 Getting Kubernetes events..."
+for i in `seq 1 $TAINT_CHECK_CYCLES`; do
+    eventnotfound=""
+    annotationnotfound=""
+    extraannotationnotfound=""
+    events=$(kubectl get events --field-selector source=aws-node-termination-handler -o json)
+    for reason in SpotInterruption PreDrain CordonAndDrain; do
+        event=$(echo $events | jq --arg REASON "$reason" '[.items[] | select(.reason==$REASON)][0]')
+        if [[ $event == "null" ]]; then
+            eventnotfound=$reason
+            break
+        fi
+        for ant in account-id availability-zone instance-id instance-life-cycle instance-type local-hostname local-ipv4 public-hostname public-ipv4 region; do
+            if [[ "$(echo $event | jq -r --arg ANT "$ant" '.metadata.annotations[$ANT]')" == "null" ]]; then
+                eventnotfound=$reason
+                annotationnotfound=$ant
+                break 2
+            fi
+        done
+        if [[ "$(echo $event | jq -r '.metadata.annotations["spot.itn.events/test"]')" != "extra-annotation" ]]; then
+            extraannotationnotfound=$reason
+            break
+        fi
+    done
+    if [ -z $eventnotfound ] && [ -z $annotationnotfound ] && [ -z $extraannotationnotfound ]; then
+        echo "✅ Spot Interruption With Events Test Passed $CLUSTER_NAME! ✅"
         exit 0
     fi
-    echo "Assertion Loop $i/$TAINT_CHECK_CYCLES, sleeping for $TAINT_CHECK_SLEEP seconds"
+    echo "Events Loop $i/$TAINT_CHECK_CYCLES, sleeping for $TAINT_CHECK_SLEEP seconds"
     sleep $TAINT_CHECK_SLEEP
 done
 
-echo "❌ regular-pod-test was NOT evicted"
-fail_and_exit 1
+if [ ! -z $eventnotfound ]; then
+    if [ ! -z $annotationnotfound ]; then
+        echo "❌ Annotation $annotationnotfound was not found on event with reason $eventnotfound"
+        fail_and_exit 1
+    fi
+    echo "❌ Event with reason $eventnotfound was not emitted"
+    fail_and_exit 1
+fi
+echo "❌ Extra annotation was not found on event with reason $extraannotationnotfound"
+fail_and_exit_1
